/* tslint:disable */
/* eslint-disable */
/**
 * Game API
 * API для игры с раундами и подсчетом очков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1RoundsIdGet200ResponseTopStatsInnerUser } from './ApiV1RoundsIdGet200ResponseTopStatsInnerUser';
import {
    ApiV1RoundsIdGet200ResponseTopStatsInnerUserFromJSON,
    ApiV1RoundsIdGet200ResponseTopStatsInnerUserFromJSONTyped,
    ApiV1RoundsIdGet200ResponseTopStatsInnerUserToJSON,
    ApiV1RoundsIdGet200ResponseTopStatsInnerUserToJSONTyped,
} from './ApiV1RoundsIdGet200ResponseTopStatsInnerUser';

/**
 * 
 * @export
 * @interface ApiV1RoundsIdGet200ResponseTopStatsInner
 */
export interface ApiV1RoundsIdGet200ResponseTopStatsInner {
    /**
     * 
     * @type {number}
     * @memberof ApiV1RoundsIdGet200ResponseTopStatsInner
     */
    taps: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1RoundsIdGet200ResponseTopStatsInner
     */
    score: number;
    /**
     * 
     * @type {ApiV1RoundsIdGet200ResponseTopStatsInnerUser}
     * @memberof ApiV1RoundsIdGet200ResponseTopStatsInner
     */
    user: ApiV1RoundsIdGet200ResponseTopStatsInnerUser;
}

/**
 * Check if a given object implements the ApiV1RoundsIdGet200ResponseTopStatsInner interface.
 */
export function instanceOfApiV1RoundsIdGet200ResponseTopStatsInner(value: object): value is ApiV1RoundsIdGet200ResponseTopStatsInner {
    if (!('taps' in value) || value['taps'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function ApiV1RoundsIdGet200ResponseTopStatsInnerFromJSON(json: any): ApiV1RoundsIdGet200ResponseTopStatsInner {
    return ApiV1RoundsIdGet200ResponseTopStatsInnerFromJSONTyped(json, false);
}

export function ApiV1RoundsIdGet200ResponseTopStatsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1RoundsIdGet200ResponseTopStatsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'taps': json['taps'],
        'score': json['score'],
        'user': ApiV1RoundsIdGet200ResponseTopStatsInnerUserFromJSON(json['user']),
    };
}

export function ApiV1RoundsIdGet200ResponseTopStatsInnerToJSON(json: any): ApiV1RoundsIdGet200ResponseTopStatsInner {
    return ApiV1RoundsIdGet200ResponseTopStatsInnerToJSONTyped(json, false);
}

export function ApiV1RoundsIdGet200ResponseTopStatsInnerToJSONTyped(value?: ApiV1RoundsIdGet200ResponseTopStatsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taps': value['taps'],
        'score': value['score'],
        'user': ApiV1RoundsIdGet200ResponseTopStatsInnerUserToJSON(value['user']),
    };
}

