/* tslint:disable */
/* eslint-disable */
/**
 * Game API
 * API для игры с раундами и подсчетом очков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1RoundsIdGet200ResponseTopStatsInner } from './ApiV1RoundsIdGet200ResponseTopStatsInner';
import {
    ApiV1RoundsIdGet200ResponseTopStatsInnerFromJSON,
    ApiV1RoundsIdGet200ResponseTopStatsInnerFromJSONTyped,
    ApiV1RoundsIdGet200ResponseTopStatsInnerToJSON,
    ApiV1RoundsIdGet200ResponseTopStatsInnerToJSONTyped,
} from './ApiV1RoundsIdGet200ResponseTopStatsInner';
import type { ApiV1RoundsGet200ResponseDataInner } from './ApiV1RoundsGet200ResponseDataInner';
import {
    ApiV1RoundsGet200ResponseDataInnerFromJSON,
    ApiV1RoundsGet200ResponseDataInnerFromJSONTyped,
    ApiV1RoundsGet200ResponseDataInnerToJSON,
    ApiV1RoundsGet200ResponseDataInnerToJSONTyped,
} from './ApiV1RoundsGet200ResponseDataInner';
import type { ApiV1RoundsIdGet200ResponseMyStats } from './ApiV1RoundsIdGet200ResponseMyStats';
import {
    ApiV1RoundsIdGet200ResponseMyStatsFromJSON,
    ApiV1RoundsIdGet200ResponseMyStatsFromJSONTyped,
    ApiV1RoundsIdGet200ResponseMyStatsToJSON,
    ApiV1RoundsIdGet200ResponseMyStatsToJSONTyped,
} from './ApiV1RoundsIdGet200ResponseMyStats';

/**
 * 
 * @export
 * @interface ApiV1RoundsIdGet200Response
 */
export interface ApiV1RoundsIdGet200Response {
    /**
     * 
     * @type {ApiV1RoundsGet200ResponseDataInner}
     * @memberof ApiV1RoundsIdGet200Response
     */
    round: ApiV1RoundsGet200ResponseDataInner;
    /**
     * 
     * @type {Array<ApiV1RoundsIdGet200ResponseTopStatsInner>}
     * @memberof ApiV1RoundsIdGet200Response
     */
    topStats: Array<ApiV1RoundsIdGet200ResponseTopStatsInner>;
    /**
     * 
     * @type {ApiV1RoundsIdGet200ResponseMyStats}
     * @memberof ApiV1RoundsIdGet200Response
     */
    myStats: ApiV1RoundsIdGet200ResponseMyStats;
}

/**
 * Check if a given object implements the ApiV1RoundsIdGet200Response interface.
 */
export function instanceOfApiV1RoundsIdGet200Response(value: object): value is ApiV1RoundsIdGet200Response {
    if (!('round' in value) || value['round'] === undefined) return false;
    if (!('topStats' in value) || value['topStats'] === undefined) return false;
    if (!('myStats' in value) || value['myStats'] === undefined) return false;
    return true;
}

export function ApiV1RoundsIdGet200ResponseFromJSON(json: any): ApiV1RoundsIdGet200Response {
    return ApiV1RoundsIdGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1RoundsIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1RoundsIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'round': ApiV1RoundsGet200ResponseDataInnerFromJSON(json['round']),
        'topStats': ((json['topStats'] as Array<any>).map(ApiV1RoundsIdGet200ResponseTopStatsInnerFromJSON)),
        'myStats': ApiV1RoundsIdGet200ResponseMyStatsFromJSON(json['myStats']),
    };
}

export function ApiV1RoundsIdGet200ResponseToJSON(json: any): ApiV1RoundsIdGet200Response {
    return ApiV1RoundsIdGet200ResponseToJSONTyped(json, false);
}

export function ApiV1RoundsIdGet200ResponseToJSONTyped(value?: ApiV1RoundsIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'round': ApiV1RoundsGet200ResponseDataInnerToJSON(value['round']),
        'topStats': ((value['topStats'] as Array<any>).map(ApiV1RoundsIdGet200ResponseTopStatsInnerToJSON)),
        'myStats': ApiV1RoundsIdGet200ResponseMyStatsToJSON(value['myStats']),
    };
}

