/* tslint:disable */
/* eslint-disable */
/**
 * Game API
 * API для игры с раундами и подсчетом очков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Unauthorized
 * @export
 * @interface ApiV1AuthLoginPost401Response
 */
export interface ApiV1AuthLoginPost401Response {
    /**
     * Error details
     * @type {string}
     * @memberof ApiV1AuthLoginPost401Response
     */
    message: string;
}

/**
 * Check if a given object implements the ApiV1AuthLoginPost401Response interface.
 */
export function instanceOfApiV1AuthLoginPost401Response(value: object): value is ApiV1AuthLoginPost401Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ApiV1AuthLoginPost401ResponseFromJSON(json: any): ApiV1AuthLoginPost401Response {
    return ApiV1AuthLoginPost401ResponseFromJSONTyped(json, false);
}

export function ApiV1AuthLoginPost401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1AuthLoginPost401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ApiV1AuthLoginPost401ResponseToJSON(json: any): ApiV1AuthLoginPost401Response {
    return ApiV1AuthLoginPost401ResponseToJSONTyped(json, false);
}

export function ApiV1AuthLoginPost401ResponseToJSONTyped(value?: ApiV1AuthLoginPost401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

