/* tslint:disable */
/* eslint-disable */
/**
 * Game API
 * API для игры с раундами и подсчетом очков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1AuthLogoutPost200Response
 */
export interface ApiV1AuthLogoutPost200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1AuthLogoutPost200Response
     */
    success: boolean;
}

/**
 * Check if a given object implements the ApiV1AuthLogoutPost200Response interface.
 */
export function instanceOfApiV1AuthLogoutPost200Response(value: object): value is ApiV1AuthLogoutPost200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function ApiV1AuthLogoutPost200ResponseFromJSON(json: any): ApiV1AuthLogoutPost200Response {
    return ApiV1AuthLogoutPost200ResponseFromJSONTyped(json, false);
}

export function ApiV1AuthLogoutPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1AuthLogoutPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function ApiV1AuthLogoutPost200ResponseToJSON(json: any): ApiV1AuthLogoutPost200Response {
    return ApiV1AuthLogoutPost200ResponseToJSONTyped(json, false);
}

export function ApiV1AuthLogoutPost200ResponseToJSONTyped(value?: ApiV1AuthLogoutPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

