/* tslint:disable */
/* eslint-disable */
/**
 * Game API
 * API для игры с раундами и подсчетом очков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1AuthLoginPost200Response
 */
export interface ApiV1AuthLoginPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthLoginPost200Response
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthLoginPost200Response
     */
    role: ApiV1AuthLoginPost200ResponseRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthLoginPost200Response
     */
    token: string;
}


/**
 * @export
 */
export const ApiV1AuthLoginPost200ResponseRoleEnum = {
    Survivor: 'SURVIVOR',
    Nikita: 'NIKITA',
    Admin: 'ADMIN'
} as const;
export type ApiV1AuthLoginPost200ResponseRoleEnum = typeof ApiV1AuthLoginPost200ResponseRoleEnum[keyof typeof ApiV1AuthLoginPost200ResponseRoleEnum];


/**
 * Check if a given object implements the ApiV1AuthLoginPost200Response interface.
 */
export function instanceOfApiV1AuthLoginPost200Response(value: object): value is ApiV1AuthLoginPost200Response {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function ApiV1AuthLoginPost200ResponseFromJSON(json: any): ApiV1AuthLoginPost200Response {
    return ApiV1AuthLoginPost200ResponseFromJSONTyped(json, false);
}

export function ApiV1AuthLoginPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1AuthLoginPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'role': json['role'],
        'token': json['token'],
    };
}

export function ApiV1AuthLoginPost200ResponseToJSON(json: any): ApiV1AuthLoginPost200Response {
    return ApiV1AuthLoginPost200ResponseToJSONTyped(json, false);
}

export function ApiV1AuthLoginPost200ResponseToJSONTyped(value?: ApiV1AuthLoginPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'role': value['role'],
        'token': value['token'],
    };
}

