/* tslint:disable */
/* eslint-disable */
/**
 * Game API
 * API для игры с раундами и подсчетом очков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1RoundsIdGet200ResponseMyStats
 */
export interface ApiV1RoundsIdGet200ResponseMyStats {
    /**
     * 
     * @type {number}
     * @memberof ApiV1RoundsIdGet200ResponseMyStats
     */
    taps: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1RoundsIdGet200ResponseMyStats
     */
    score: number;
}

/**
 * Check if a given object implements the ApiV1RoundsIdGet200ResponseMyStats interface.
 */
export function instanceOfApiV1RoundsIdGet200ResponseMyStats(value: object): value is ApiV1RoundsIdGet200ResponseMyStats {
    if (!('taps' in value) || value['taps'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function ApiV1RoundsIdGet200ResponseMyStatsFromJSON(json: any): ApiV1RoundsIdGet200ResponseMyStats {
    return ApiV1RoundsIdGet200ResponseMyStatsFromJSONTyped(json, false);
}

export function ApiV1RoundsIdGet200ResponseMyStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1RoundsIdGet200ResponseMyStats {
    if (json == null) {
        return json;
    }
    return {
        
        'taps': json['taps'],
        'score': json['score'],
    };
}

export function ApiV1RoundsIdGet200ResponseMyStatsToJSON(json: any): ApiV1RoundsIdGet200ResponseMyStats {
    return ApiV1RoundsIdGet200ResponseMyStatsToJSONTyped(json, false);
}

export function ApiV1RoundsIdGet200ResponseMyStatsToJSONTyped(value?: ApiV1RoundsIdGet200ResponseMyStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taps': value['taps'],
        'score': value['score'],
    };
}

