/* tslint:disable */
/* eslint-disable */
/**
 * Game API
 * API для игры с раундами и подсчетом очков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1RoundsIdTapPost200Response
 */
export interface ApiV1RoundsIdTapPost200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiV1RoundsIdTapPost200Response
     */
    taps: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1RoundsIdTapPost200Response
     */
    score: number;
}

/**
 * Check if a given object implements the ApiV1RoundsIdTapPost200Response interface.
 */
export function instanceOfApiV1RoundsIdTapPost200Response(value: object): value is ApiV1RoundsIdTapPost200Response {
    if (!('taps' in value) || value['taps'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function ApiV1RoundsIdTapPost200ResponseFromJSON(json: any): ApiV1RoundsIdTapPost200Response {
    return ApiV1RoundsIdTapPost200ResponseFromJSONTyped(json, false);
}

export function ApiV1RoundsIdTapPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1RoundsIdTapPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'taps': json['taps'],
        'score': json['score'],
    };
}

export function ApiV1RoundsIdTapPost200ResponseToJSON(json: any): ApiV1RoundsIdTapPost200Response {
    return ApiV1RoundsIdTapPost200ResponseToJSONTyped(json, false);
}

export function ApiV1RoundsIdTapPost200ResponseToJSONTyped(value?: ApiV1RoundsIdTapPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taps': value['taps'],
        'score': value['score'],
    };
}

