/* tslint:disable */
/* eslint-disable */
/**
 * Game API
 * API для игры с раундами и подсчетом очков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1AuthLoginPostRequest
 */
export interface ApiV1AuthLoginPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthLoginPostRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthLoginPostRequest
     */
    password: string;
}

/**
 * Check if a given object implements the ApiV1AuthLoginPostRequest interface.
 */
export function instanceOfApiV1AuthLoginPostRequest(value: object): value is ApiV1AuthLoginPostRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function ApiV1AuthLoginPostRequestFromJSON(json: any): ApiV1AuthLoginPostRequest {
    return ApiV1AuthLoginPostRequestFromJSONTyped(json, false);
}

export function ApiV1AuthLoginPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1AuthLoginPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function ApiV1AuthLoginPostRequestToJSON(json: any): ApiV1AuthLoginPostRequest {
    return ApiV1AuthLoginPostRequestToJSONTyped(json, false);
}

export function ApiV1AuthLoginPostRequestToJSONTyped(value?: ApiV1AuthLoginPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

