/* tslint:disable */
/* eslint-disable */
/**
 * Game API
 * API для игры с раундами и подсчетом очков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Resource not found response
 * @export
 * @interface ApiV1AuthLoginPost404Response
 */
export interface ApiV1AuthLoginPost404Response {
    /**
     * Error details
     * @type {string}
     * @memberof ApiV1AuthLoginPost404Response
     */
    message: string;
}

/**
 * Check if a given object implements the ApiV1AuthLoginPost404Response interface.
 */
export function instanceOfApiV1AuthLoginPost404Response(value: object): value is ApiV1AuthLoginPost404Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ApiV1AuthLoginPost404ResponseFromJSON(json: any): ApiV1AuthLoginPost404Response {
    return ApiV1AuthLoginPost404ResponseFromJSONTyped(json, false);
}

export function ApiV1AuthLoginPost404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1AuthLoginPost404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ApiV1AuthLoginPost404ResponseToJSON(json: any): ApiV1AuthLoginPost404Response {
    return ApiV1AuthLoginPost404ResponseToJSONTyped(json, false);
}

export function ApiV1AuthLoginPost404ResponseToJSONTyped(value?: ApiV1AuthLoginPost404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

