/* tslint:disable */
/* eslint-disable */
/**
 * Game API
 * API для игры с раундами и подсчетом очков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1RoundsGet200ResponsePagination
 */
export interface ApiV1RoundsGet200ResponsePagination {
    /**
     * 
     * @type {number}
     * @memberof ApiV1RoundsGet200ResponsePagination
     */
    limit: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1RoundsGet200ResponsePagination
     */
    nextCursor: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1RoundsGet200ResponsePagination
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the ApiV1RoundsGet200ResponsePagination interface.
 */
export function instanceOfApiV1RoundsGet200ResponsePagination(value: object): value is ApiV1RoundsGet200ResponsePagination {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function ApiV1RoundsGet200ResponsePaginationFromJSON(json: any): ApiV1RoundsGet200ResponsePagination {
    return ApiV1RoundsGet200ResponsePaginationFromJSONTyped(json, false);
}

export function ApiV1RoundsGet200ResponsePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1RoundsGet200ResponsePagination {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'],
        'nextCursor': json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function ApiV1RoundsGet200ResponsePaginationToJSON(json: any): ApiV1RoundsGet200ResponsePagination {
    return ApiV1RoundsGet200ResponsePaginationToJSONTyped(json, false);
}

export function ApiV1RoundsGet200ResponsePaginationToJSONTyped(value?: ApiV1RoundsGet200ResponsePagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}

