/* tslint:disable */
/* eslint-disable */
/**
 * Game API
 * API для игры с раундами и подсчетом очков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1RoundsIdGet200ResponseTopStatsInnerUser
 */
export interface ApiV1RoundsIdGet200ResponseTopStatsInnerUser {
    /**
     * 
     * @type {string}
     * @memberof ApiV1RoundsIdGet200ResponseTopStatsInnerUser
     */
    username: string;
}

/**
 * Check if a given object implements the ApiV1RoundsIdGet200ResponseTopStatsInnerUser interface.
 */
export function instanceOfApiV1RoundsIdGet200ResponseTopStatsInnerUser(value: object): value is ApiV1RoundsIdGet200ResponseTopStatsInnerUser {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function ApiV1RoundsIdGet200ResponseTopStatsInnerUserFromJSON(json: any): ApiV1RoundsIdGet200ResponseTopStatsInnerUser {
    return ApiV1RoundsIdGet200ResponseTopStatsInnerUserFromJSONTyped(json, false);
}

export function ApiV1RoundsIdGet200ResponseTopStatsInnerUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1RoundsIdGet200ResponseTopStatsInnerUser {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
    };
}

export function ApiV1RoundsIdGet200ResponseTopStatsInnerUserToJSON(json: any): ApiV1RoundsIdGet200ResponseTopStatsInnerUser {
    return ApiV1RoundsIdGet200ResponseTopStatsInnerUserToJSONTyped(json, false);
}

export function ApiV1RoundsIdGet200ResponseTopStatsInnerUserToJSONTyped(value?: ApiV1RoundsIdGet200ResponseTopStatsInnerUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
    };
}

