/* tslint:disable */
/* eslint-disable */
/**
 * Game API
 * API для игры с раундами и подсчетом очков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1AuthMeGet200Response
 */
export interface ApiV1AuthMeGet200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthMeGet200Response
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthMeGet200Response
     */
    role: ApiV1AuthMeGet200ResponseRoleEnum;
}


/**
 * @export
 */
export const ApiV1AuthMeGet200ResponseRoleEnum = {
    Survivor: 'SURVIVOR',
    Nikita: 'NIKITA',
    Admin: 'ADMIN'
} as const;
export type ApiV1AuthMeGet200ResponseRoleEnum = typeof ApiV1AuthMeGet200ResponseRoleEnum[keyof typeof ApiV1AuthMeGet200ResponseRoleEnum];


/**
 * Check if a given object implements the ApiV1AuthMeGet200Response interface.
 */
export function instanceOfApiV1AuthMeGet200Response(value: object): value is ApiV1AuthMeGet200Response {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function ApiV1AuthMeGet200ResponseFromJSON(json: any): ApiV1AuthMeGet200Response {
    return ApiV1AuthMeGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1AuthMeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1AuthMeGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'role': json['role'],
    };
}

export function ApiV1AuthMeGet200ResponseToJSON(json: any): ApiV1AuthMeGet200Response {
    return ApiV1AuthMeGet200ResponseToJSONTyped(json, false);
}

export function ApiV1AuthMeGet200ResponseToJSONTyped(value?: ApiV1AuthMeGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'role': value['role'],
    };
}

