/* tslint:disable */
/* eslint-disable */
/**
 * Game API
 * API для игры с раундами и подсчетом очков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1RoundsGet200ResponsePagination } from './ApiV1RoundsGet200ResponsePagination';
import {
    ApiV1RoundsGet200ResponsePaginationFromJSON,
    ApiV1RoundsGet200ResponsePaginationFromJSONTyped,
    ApiV1RoundsGet200ResponsePaginationToJSON,
    ApiV1RoundsGet200ResponsePaginationToJSONTyped,
} from './ApiV1RoundsGet200ResponsePagination';
import type { ApiV1RoundsGet200ResponseDataInner } from './ApiV1RoundsGet200ResponseDataInner';
import {
    ApiV1RoundsGet200ResponseDataInnerFromJSON,
    ApiV1RoundsGet200ResponseDataInnerFromJSONTyped,
    ApiV1RoundsGet200ResponseDataInnerToJSON,
    ApiV1RoundsGet200ResponseDataInnerToJSONTyped,
} from './ApiV1RoundsGet200ResponseDataInner';

/**
 * 
 * @export
 * @interface ApiV1RoundsGet200Response
 */
export interface ApiV1RoundsGet200Response {
    /**
     * 
     * @type {Array<ApiV1RoundsGet200ResponseDataInner>}
     * @memberof ApiV1RoundsGet200Response
     */
    data: Array<ApiV1RoundsGet200ResponseDataInner>;
    /**
     * 
     * @type {ApiV1RoundsGet200ResponsePagination}
     * @memberof ApiV1RoundsGet200Response
     */
    pagination: ApiV1RoundsGet200ResponsePagination;
}

/**
 * Check if a given object implements the ApiV1RoundsGet200Response interface.
 */
export function instanceOfApiV1RoundsGet200Response(value: object): value is ApiV1RoundsGet200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ApiV1RoundsGet200ResponseFromJSON(json: any): ApiV1RoundsGet200Response {
    return ApiV1RoundsGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1RoundsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1RoundsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ApiV1RoundsGet200ResponseDataInnerFromJSON)),
        'pagination': ApiV1RoundsGet200ResponsePaginationFromJSON(json['pagination']),
    };
}

export function ApiV1RoundsGet200ResponseToJSON(json: any): ApiV1RoundsGet200Response {
    return ApiV1RoundsGet200ResponseToJSONTyped(json, false);
}

export function ApiV1RoundsGet200ResponseToJSONTyped(value?: ApiV1RoundsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ApiV1RoundsGet200ResponseDataInnerToJSON)),
        'pagination': ApiV1RoundsGet200ResponsePaginationToJSON(value['pagination']),
    };
}

