/* tslint:disable */
/* eslint-disable */
/**
 * Game API
 * API для игры с раундами и подсчетом очков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1RoundsGet200ResponseDataInner
 */
export interface ApiV1RoundsGet200ResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV1RoundsGet200ResponseDataInner
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiV1RoundsGet200ResponseDataInner
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApiV1RoundsGet200ResponseDataInner
     */
    endTime: Date;
    /**
     * 
     * @type {number}
     * @memberof ApiV1RoundsGet200ResponseDataInner
     */
    totalScore: number;
    /**
     * 
     * @type {Date}
     * @memberof ApiV1RoundsGet200ResponseDataInner
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ApiV1RoundsGet200ResponseDataInner interface.
 */
export function instanceOfApiV1RoundsGet200ResponseDataInner(value: object): value is ApiV1RoundsGet200ResponseDataInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('totalScore' in value) || value['totalScore'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ApiV1RoundsGet200ResponseDataInnerFromJSON(json: any): ApiV1RoundsGet200ResponseDataInner {
    return ApiV1RoundsGet200ResponseDataInnerFromJSONTyped(json, false);
}

export function ApiV1RoundsGet200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1RoundsGet200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'startTime': (new Date(json['startTime'])),
        'endTime': (new Date(json['endTime'])),
        'totalScore': json['totalScore'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ApiV1RoundsGet200ResponseDataInnerToJSON(json: any): ApiV1RoundsGet200ResponseDataInner {
    return ApiV1RoundsGet200ResponseDataInnerToJSONTyped(json, false);
}

export function ApiV1RoundsGet200ResponseDataInnerToJSONTyped(value?: ApiV1RoundsGet200ResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'startTime': value['startTime'].toISOString(),
        'endTime': value['endTime'].toISOString(),
        'totalScore': value['totalScore'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

