/* tslint:disable */
/* eslint-disable */
/**
 * Game API
 * API для игры с раундами и подсчетом очков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiV1AuthLoginPost200Response,
  ApiV1AuthLoginPost400Response,
  ApiV1AuthLoginPost401Response,
  ApiV1AuthLoginPost403Response,
  ApiV1AuthLoginPost404Response,
  ApiV1AuthLoginPost500Response,
  ApiV1AuthLoginPostRequest,
  ApiV1AuthLogoutPost200Response,
  ApiV1AuthMeGet200Response,
} from '../models/index';
import {
    ApiV1AuthLoginPost200ResponseFromJSON,
    ApiV1AuthLoginPost200ResponseToJSON,
    ApiV1AuthLoginPost400ResponseFromJSON,
    ApiV1AuthLoginPost400ResponseToJSON,
    ApiV1AuthLoginPost401ResponseFromJSON,
    ApiV1AuthLoginPost401ResponseToJSON,
    ApiV1AuthLoginPost403ResponseFromJSON,
    ApiV1AuthLoginPost403ResponseToJSON,
    ApiV1AuthLoginPost404ResponseFromJSON,
    ApiV1AuthLoginPost404ResponseToJSON,
    ApiV1AuthLoginPost500ResponseFromJSON,
    ApiV1AuthLoginPost500ResponseToJSON,
    ApiV1AuthLoginPostRequestFromJSON,
    ApiV1AuthLoginPostRequestToJSON,
    ApiV1AuthLogoutPost200ResponseFromJSON,
    ApiV1AuthLogoutPost200ResponseToJSON,
    ApiV1AuthMeGet200ResponseFromJSON,
    ApiV1AuthMeGet200ResponseToJSON,
} from '../models/index';

export interface ApiV1AuthLoginPostOperationRequest {
    apiV1AuthLoginPostRequest: ApiV1AuthLoginPostRequest;
}

/**
 * AuthApi - interface
 * 
 * @export
 * @interface AuthApiInterface
 */
export interface AuthApiInterface {
    /**
     * Login or register user
     * @param {ApiV1AuthLoginPostRequest} apiV1AuthLoginPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    apiV1AuthLoginPostRaw(requestParameters: ApiV1AuthLoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1AuthLoginPost200Response>>;

    /**
     * Login or register user
     */
    apiV1AuthLoginPost(requestParameters: ApiV1AuthLoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1AuthLoginPost200Response>;

    /**
     * Logout user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    apiV1AuthLogoutPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1AuthLogoutPost200Response>>;

    /**
     * Logout user
     */
    apiV1AuthLogoutPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1AuthLogoutPost200Response>;

    /**
     * Get current authenticated user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    apiV1AuthMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1AuthMeGet200Response>>;

    /**
     * Get current authenticated user
     */
    apiV1AuthMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1AuthMeGet200Response>;

}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI implements AuthApiInterface {

    /**
     * Login or register user
     */
    async apiV1AuthLoginPostRaw(requestParameters: ApiV1AuthLoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1AuthLoginPost200Response>> {
        if (requestParameters['apiV1AuthLoginPostRequest'] == null) {
            throw new runtime.RequiredError(
                'apiV1AuthLoginPostRequest',
                'Required parameter "apiV1AuthLoginPostRequest" was null or undefined when calling apiV1AuthLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV1AuthLoginPostRequestToJSON(requestParameters['apiV1AuthLoginPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1AuthLoginPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Login or register user
     */
    async apiV1AuthLoginPost(requestParameters: ApiV1AuthLoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1AuthLoginPost200Response> {
        const response = await this.apiV1AuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Logout user
     */
    async apiV1AuthLogoutPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1AuthLogoutPost200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/auth/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1AuthLogoutPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Logout user
     */
    async apiV1AuthLogoutPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1AuthLogoutPost200Response> {
        const response = await this.apiV1AuthLogoutPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get current authenticated user
     */
    async apiV1AuthMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1AuthMeGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/auth/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1AuthMeGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get current authenticated user
     */
    async apiV1AuthMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1AuthMeGet200Response> {
        const response = await this.apiV1AuthMeGetRaw(initOverrides);
        return await response.value();
    }

}
