/* tslint:disable */
/* eslint-disable */
/**
 * Game API
 * API для игры с раундами и подсчетом очков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiV1AuthLoginPost400Response,
  ApiV1AuthLoginPost401Response,
  ApiV1AuthLoginPost403Response,
  ApiV1AuthLoginPost404Response,
  ApiV1AuthLoginPost500Response,
  ApiV1RoundsGet200Response,
  ApiV1RoundsGet200ResponseDataInner,
  ApiV1RoundsIdGet200Response,
  ApiV1RoundsIdTapPost200Response,
} from '../models/index';
import {
    ApiV1AuthLoginPost400ResponseFromJSON,
    ApiV1AuthLoginPost400ResponseToJSON,
    ApiV1AuthLoginPost401ResponseFromJSON,
    ApiV1AuthLoginPost401ResponseToJSON,
    ApiV1AuthLoginPost403ResponseFromJSON,
    ApiV1AuthLoginPost403ResponseToJSON,
    ApiV1AuthLoginPost404ResponseFromJSON,
    ApiV1AuthLoginPost404ResponseToJSON,
    ApiV1AuthLoginPost500ResponseFromJSON,
    ApiV1AuthLoginPost500ResponseToJSON,
    ApiV1RoundsGet200ResponseFromJSON,
    ApiV1RoundsGet200ResponseToJSON,
    ApiV1RoundsGet200ResponseDataInnerFromJSON,
    ApiV1RoundsGet200ResponseDataInnerToJSON,
    ApiV1RoundsIdGet200ResponseFromJSON,
    ApiV1RoundsIdGet200ResponseToJSON,
    ApiV1RoundsIdTapPost200ResponseFromJSON,
    ApiV1RoundsIdTapPost200ResponseToJSON,
} from '../models/index';

export interface ApiV1RoundsGetRequest {
    cursor?: string;
    limit?: number;
    status?: ApiV1RoundsGetStatusEnum;
}

export interface ApiV1RoundsIdGetRequest {
    id: string;
}

export interface ApiV1RoundsIdTapPostRequest {
    id: string;
}

/**
 * RoundsApi - interface
 * 
 * @export
 * @interface RoundsApiInterface
 */
export interface RoundsApiInterface {
    /**
     * Get all rounds with pagination
     * @param {string} [cursor] 
     * @param {number} [limit] 
     * @param {'active' | 'cooldown' | 'finished'} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoundsApiInterface
     */
    apiV1RoundsGetRaw(requestParameters: ApiV1RoundsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1RoundsGet200Response>>;

    /**
     * Get all rounds with pagination
     */
    apiV1RoundsGet(requestParameters: ApiV1RoundsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1RoundsGet200Response>;

    /**
     * Get round details
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoundsApiInterface
     */
    apiV1RoundsIdGetRaw(requestParameters: ApiV1RoundsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1RoundsIdGet200Response>>;

    /**
     * Get round details
     */
    apiV1RoundsIdGet(requestParameters: ApiV1RoundsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1RoundsIdGet200Response>;

    /**
     * Register a tap in the round
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoundsApiInterface
     */
    apiV1RoundsIdTapPostRaw(requestParameters: ApiV1RoundsIdTapPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1RoundsIdTapPost200Response>>;

    /**
     * Register a tap in the round
     */
    apiV1RoundsIdTapPost(requestParameters: ApiV1RoundsIdTapPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1RoundsIdTapPost200Response>;

    /**
     * Create a new round (Admin only)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoundsApiInterface
     */
    apiV1RoundsPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1RoundsGet200ResponseDataInner>>;

    /**
     * Create a new round (Admin only)
     */
    apiV1RoundsPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1RoundsGet200ResponseDataInner>;

}

/**
 * 
 */
export class RoundsApi extends runtime.BaseAPI implements RoundsApiInterface {

    /**
     * Get all rounds with pagination
     */
    async apiV1RoundsGetRaw(requestParameters: ApiV1RoundsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1RoundsGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/rounds`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1RoundsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get all rounds with pagination
     */
    async apiV1RoundsGet(requestParameters: ApiV1RoundsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1RoundsGet200Response> {
        const response = await this.apiV1RoundsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get round details
     */
    async apiV1RoundsIdGetRaw(requestParameters: ApiV1RoundsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1RoundsIdGet200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1RoundsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/rounds/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1RoundsIdGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get round details
     */
    async apiV1RoundsIdGet(requestParameters: ApiV1RoundsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1RoundsIdGet200Response> {
        const response = await this.apiV1RoundsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Register a tap in the round
     */
    async apiV1RoundsIdTapPostRaw(requestParameters: ApiV1RoundsIdTapPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1RoundsIdTapPost200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1RoundsIdTapPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/rounds/{id}/tap`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1RoundsIdTapPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Register a tap in the round
     */
    async apiV1RoundsIdTapPost(requestParameters: ApiV1RoundsIdTapPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1RoundsIdTapPost200Response> {
        const response = await this.apiV1RoundsIdTapPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new round (Admin only)
     */
    async apiV1RoundsPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1RoundsGet200ResponseDataInner>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/rounds`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1RoundsGet200ResponseDataInnerFromJSON(jsonValue));
    }

    /**
     * Create a new round (Admin only)
     */
    async apiV1RoundsPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1RoundsGet200ResponseDataInner> {
        const response = await this.apiV1RoundsPostRaw(initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiV1RoundsGetStatusEnum = {
    Active: 'active',
    Cooldown: 'cooldown',
    Finished: 'finished'
} as const;
export type ApiV1RoundsGetStatusEnum = typeof ApiV1RoundsGetStatusEnum[keyof typeof ApiV1RoundsGetStatusEnum];
